server:
  port: 9120
management:
  server:
    port: 9121
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: env, health

# logging
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO


spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
